# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'align_FS_panel.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AlignFS_panel(object):
    def setupUi(self, AlignFS_panel):
        AlignFS_panel.setObjectName("AlignFS_panel")
        AlignFS_panel.setEnabled(True)
        AlignFS_panel.resize(999, 675)
        self.centralwidget = QtWidgets.QWidget(AlignFS_panel)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.MainPlot = PlotWidget(self.centralwidget)
        self.MainPlot.setGeometry(QtCore.QRect(30, 10, 401, 341))
        self.MainPlot.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.MainPlot.setObjectName("MainPlot")
        self.cut1_Plot = PlotWidget(self.centralwidget)
        self.cut1_Plot.setGeometry(QtCore.QRect(440, 10, 261, 341))
        self.cut1_Plot.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.cut1_Plot.setObjectName("cut1_Plot")
        self.cut2_Plot = PlotWidget(self.centralwidget)
        self.cut2_Plot.setGeometry(QtCore.QRect(710, 10, 261, 341))
        self.cut2_Plot.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.cut2_Plot.setObjectName("cut2_Plot")
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 360, 541, 101))
        self.graphicsView.setObjectName("graphicsView")
        self.HCutOff = QtWidgets.QSlider(self.centralwidget)
        self.HCutOff.setGeometry(QtCore.QRect(650, 400, 251, 22))
        self.HCutOff.setMaximum(100)
        self.HCutOff.setProperty("value", 100)
        self.HCutOff.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.HCutOff.setInvertedAppearance(False)
        self.HCutOff.setInvertedControls(False)
        self.HCutOff.setObjectName("HCutOff")
        self.LCutOff = QtWidgets.QSlider(self.centralwidget)
        self.LCutOff.setGeometry(QtCore.QRect(650, 430, 251, 22))
        self.LCutOff.setMaximum(100)
        self.LCutOff.setProperty("value", 0)
        self.LCutOff.setSliderPosition(0)
        self.LCutOff.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.LCutOff.setInvertedAppearance(False)
        self.LCutOff.setInvertedControls(False)
        self.LCutOff.setObjectName("LCutOff")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(910, 420, 21, 21))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.Cmaps = QtWidgets.QComboBox(self.centralwidget)
        self.Cmaps.setGeometry(QtCore.QRect(610, 370, 151, 26))
        self.Cmaps.setEditable(False)
        self.Cmaps.setCurrentText("")
        self.Cmaps.setObjectName("Cmaps")
        self.Span_DC = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Span_DC.setGeometry(QtCore.QRect(100, 550, 91, 24))
        self.Span_DC.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.Span_DC.setObjectName("Span_DC")
        self.Rot_select = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Rot_select.setGeometry(QtCore.QRect(100, 580, 91, 24))
        self.Rot_select.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.Rot_select.setObjectName("Rot_select")
        self.Delta_DCspan = QtWidgets.QLineEdit(self.centralwidget)
        self.Delta_DCspan.setGeometry(QtCore.QRect(200, 550, 61, 24))
        self.Delta_DCspan.setObjectName("Delta_DCspan")
        self.Delta_Rot = QtWidgets.QLineEdit(self.centralwidget)
        self.Delta_Rot.setGeometry(QtCore.QRect(200, 580, 61, 24))
        self.Delta_Rot.setObjectName("Delta_Rot")
        self.LabelStep = QtWidgets.QLabel(self.centralwidget)
        self.LabelStep.setGeometry(QtCore.QRect(210, 610, 60, 16))
        self.LabelStep.setObjectName("LabelStep")
        self.Label_DC = QtWidgets.QLabel(self.centralwidget)
        self.Label_DC.setGeometry(QtCore.QRect(30, 555, 60, 16))
        self.Label_DC.setObjectName("Label_DC")
        self.Label_Rot = QtWidgets.QLabel(self.centralwidget)
        self.Label_Rot.setGeometry(QtCore.QRect(30, 585, 60, 16))
        self.Label_Rot.setObjectName("Label_Rot")
        self.Cen_label = QtWidgets.QLabel(self.centralwidget)
        self.Cen_label.setGeometry(QtCore.QRect(330, 480, 171, 16))
        self.Cen_label.setObjectName("Cen_label")
        self.Label_X_cen = QtWidgets.QLabel(self.centralwidget)
        self.Label_X_cen.setGeometry(QtCore.QRect(329, 530, 71, 20))
        self.Label_X_cen.setObjectName("Label_X_cen")
        self.Label_Y_cen = QtWidgets.QLabel(self.centralwidget)
        self.Label_Y_cen.setGeometry(QtCore.QRect(329, 560, 71, 20))
        self.Label_Y_cen.setObjectName("Label_Y_cen")
        self.X_cen = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.X_cen.setGeometry(QtCore.QRect(410, 530, 91, 24))
        self.X_cen.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.X_cen.setObjectName("X_cen")
        self.Y_cen = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Y_cen.setGeometry(QtCore.QRect(410, 560, 91, 24))
        self.Y_cen.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.Y_cen.setObjectName("Y_cen")
        self.Delta_X_cen = QtWidgets.QLineEdit(self.centralwidget)
        self.Delta_X_cen.setGeometry(QtCore.QRect(510, 530, 61, 24))
        self.Delta_X_cen.setObjectName("Delta_X_cen")
        self.Delta_Y_cen = QtWidgets.QLineEdit(self.centralwidget)
        self.Delta_Y_cen.setGeometry(QtCore.QRect(510, 560, 61, 24))
        self.Delta_Y_cen.setObjectName("Delta_Y_cen")
        self.Auto_cen = QtWidgets.QPushButton(self.centralwidget)
        self.Auto_cen.setGeometry(QtCore.QRect(430, 490, 113, 32))
        self.Auto_cen.setObjectName("Auto_cen")
        self.align_tool_shape = QtWidgets.QComboBox(self.centralwidget)
        self.align_tool_shape.setGeometry(QtCore.QRect(640, 510, 121, 26))
        self.align_tool_shape.setEditable(False)
        self.align_tool_shape.setCurrentText("")
        self.align_tool_shape.setObjectName("align_tool_shape")
        self.align_tool_size = QtWidgets.QSlider(self.centralwidget)
        self.align_tool_size.setGeometry(QtCore.QRect(780, 510, 111, 22))
        self.align_tool_size.setMaximum(100)
        self.align_tool_size.setProperty("value", 50)
        self.align_tool_size.setSliderPosition(50)
        self.align_tool_size.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.align_tool_size.setInvertedAppearance(False)
        self.align_tool_size.setInvertedControls(False)
        self.align_tool_size.setObjectName("align_tool_size")
        self.Label_En = QtWidgets.QLabel(self.centralwidget)
        self.Label_En.setGeometry(QtCore.QRect(30, 495, 60, 16))
        self.Label_En.setObjectName("Label_En")
        self.Label_dE = QtWidgets.QLabel(self.centralwidget)
        self.Label_dE.setGeometry(QtCore.QRect(30, 525, 60, 16))
        self.Label_dE.setObjectName("Label_dE")
        self.dE_select = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dE_select.setGeometry(QtCore.QRect(100, 520, 91, 24))
        self.dE_select.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.dE_select.setObjectName("dE_select")
        self.Delta_dE = QtWidgets.QLineEdit(self.centralwidget)
        self.Delta_dE.setGeometry(QtCore.QRect(200, 520, 61, 24))
        self.Delta_dE.setObjectName("Delta_dE")
        self.set_norm = QtWidgets.QPushButton(self.centralwidget)
        self.set_norm.setGeometry(QtCore.QRect(350, 590, 113, 32))
        self.set_norm.setObjectName("set_norm")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(880, 600, 113, 32))
        self.exit.setObjectName("exit")
        self.Cen_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Cen_label_2.setGeometry(QtCore.QRect(610, 480, 171, 16))
        self.Cen_label_2.setObjectName("Cen_label_2")
        self.En_select = QtWidgets.QSlider(self.centralwidget)
        self.En_select.setGeometry(QtCore.QRect(100, 490, 161, 22))
        self.En_select.setMaximum(100)
        self.En_select.setProperty("value", 100)
        self.En_select.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.En_select.setInvertedAppearance(False)
        self.En_select.setInvertedControls(False)
        self.En_select.setObjectName("En_select")
        AlignFS_panel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AlignFS_panel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 22))
        self.menubar.setObjectName("menubar")
        AlignFS_panel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AlignFS_panel)
        self.statusbar.setObjectName("statusbar")
        AlignFS_panel.setStatusBar(self.statusbar)

        self.retranslateUi(AlignFS_panel)
        QtCore.QMetaObject.connectSlotsByName(AlignFS_panel)

    def retranslateUi(self, AlignFS_panel):
        _translate = QtCore.QCoreApplication.translate
        AlignFS_panel.setWindowTitle(_translate("AlignFS_panel", "Align FS"))
        self.LabelStep.setText(_translate("AlignFS_panel", "Step"))
        self.Label_DC.setText(_translate("AlignFS_panel", "DC int."))
        self.Label_Rot.setText(_translate("AlignFS_panel", "Rot angle"))
        self.Cen_label.setText(_translate("AlignFS_panel", "Centering:"))
        self.Label_X_cen.setText(_translate("AlignFS_panel", "theta_par"))
        self.Label_Y_cen.setText(_translate("AlignFS_panel", "map_angle"))
        self.Delta_X_cen.setText(_translate("AlignFS_panel", "1"))
        self.Delta_Y_cen.setText(_translate("AlignFS_panel", "1"))
        self.Auto_cen.setText(_translate("AlignFS_panel", "Auto"))
        self.Label_En.setText(_translate("AlignFS_panel", "Energy"))
        self.Label_dE.setText(_translate("AlignFS_panel", "dE"))
        self.set_norm.setText(_translate("AlignFS_panel", "Set"))
        self.exit.setText(_translate("AlignFS_panel", "Exit"))
        self.Cen_label_2.setText(_translate("AlignFS_panel", "Alignment aid:"))


from pyqtgraph import GraphicsLayoutWidget, PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlignFS_panel = QtWidgets.QMainWindow()
    ui = Ui_AlignFS_panel()
    ui.setupUi(AlignFS_panel)
    AlignFS_panel.show()
    sys.exit(app.exec_())
