# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'disp4d_panel.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_disp4d_panel(object):
    def setupUi(self, disp4d_panel):
        disp4d_panel.setObjectName("disp4d_panel")
        disp4d_panel.setEnabled(True)
        disp4d_panel.resize(1180, 665)
        self.centralwidget = QtWidgets.QWidget(disp4d_panel)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.CursorMode = QtWidgets.QLabel(self.centralwidget)
        self.CursorMode.setGeometry(QtCore.QRect(1010, 590, 171, 16))
        self.CursorMode.setObjectName("CursorMode")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1181, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.map = QtWidgets.QWidget()
        self.map.setObjectName("map")
        self.EDCPlot = PlotWidget(self.map)
        self.EDCPlot.setGeometry(QtCore.QRect(820, 0, 191, 381))
        self.EDCPlot.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.EDCPlot.setObjectName("EDCPlot")
        self.CursorStats = GraphicsLayoutWidget(self.map)
        self.CursorStats.setGeometry(QtCore.QRect(20, 380, 371, 161))
        self.CursorStats.setObjectName("CursorStats")
        self.MainPlot = PlotWidget(self.map)
        self.MainPlot.setGeometry(QtCore.QRect(470, 0, 351, 381))
        self.MainPlot.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MainPlot.setObjectName("MainPlot")
        self.MDCPlot = PlotWidget(self.map)
        self.MDCPlot.setGeometry(QtCore.QRect(470, 380, 351, 161))
        self.MDCPlot.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MDCPlot.setObjectName("MDCPlot")
        self.MapPlot = PlotWidget(self.map)
        self.MapPlot.setGeometry(QtCore.QRect(20, 90, 321, 281))
        self.MapPlot.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MapPlot.setObjectName("MapPlot")
        self.x1_select = QtWidgets.QSlider(self.map)
        self.x1_select.setGeometry(QtCore.QRect(50, 20, 251, 22))
        self.x1_select.setMaximum(100)
        self.x1_select.setProperty("value", 0)
        self.x1_select.setOrientation(QtCore.Qt.Horizontal)
        self.x1_select.setInvertedAppearance(False)
        self.x1_select.setInvertedControls(False)
        self.x1_select.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.x1_select.setObjectName("x1_select")
        self.x2_select = QtWidgets.QSlider(self.map)
        self.x2_select.setGeometry(QtCore.QRect(50, 50, 251, 22))
        self.x2_select.setMaximum(100)
        self.x2_select.setProperty("value", 0)
        self.x2_select.setSliderPosition(0)
        self.x2_select.setOrientation(QtCore.Qt.Horizontal)
        self.x2_select.setInvertedAppearance(False)
        self.x2_select.setInvertedControls(False)
        self.x2_select.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.x2_select.setObjectName("x2_select")
        self.Label_xsel1 = QtWidgets.QLabel(self.map)
        self.Label_xsel1.setGeometry(QtCore.QRect(20, 20, 21, 16))
        self.Label_xsel1.setObjectName("Label_xsel1")
        self.Label_xsel2 = QtWidgets.QLabel(self.map)
        self.Label_xsel2.setGeometry(QtCore.QRect(20, 50, 21, 16))
        self.Label_xsel2.setObjectName("Label_xsel2")
        self.Bin_x2 = QtWidgets.QLineEdit(self.map)
        self.Bin_x2.setGeometry(QtCore.QRect(310, 50, 61, 24))
        self.Bin_x2.setObjectName("Bin_x2")
        self.Bin_x1 = QtWidgets.QLineEdit(self.map)
        self.Bin_x1.setGeometry(QtCore.QRect(310, 20, 61, 24))
        self.Bin_x1.setObjectName("Bin_x1")
        self.Bin_label = QtWidgets.QLabel(self.map)
        self.Bin_label.setGeometry(QtCore.QRect(330, 0, 60, 16))
        self.Bin_label.setObjectName("Bin_label")
        self.IntX_sel1 = QtWidgets.QCheckBox(self.map)
        self.IntX_sel1.setGeometry(QtCore.QRect(1100, 500, 51, 21))
        self.IntX_sel1.setObjectName("IntX_sel1")
        self.SpanY_1 = QtWidgets.QDoubleSpinBox(self.map)
        self.SpanY_1.setGeometry(QtCore.QRect(930, 530, 91, 24))
        self.SpanY_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpanY_1.setObjectName("SpanY_1")
        self.LCutOff_1 = QtWidgets.QSlider(self.map)
        self.LCutOff_1.setGeometry(QtCore.QRect(840, 450, 251, 22))
        self.LCutOff_1.setMaximum(100)
        self.LCutOff_1.setProperty("value", 0)
        self.LCutOff_1.setSliderPosition(0)
        self.LCutOff_1.setOrientation(QtCore.Qt.Horizontal)
        self.LCutOff_1.setInvertedAppearance(False)
        self.LCutOff_1.setInvertedControls(False)
        self.LCutOff_1.setObjectName("LCutOff_1")
        self.LabelX_1 = QtWidgets.QLabel(self.map)
        self.LabelX_1.setGeometry(QtCore.QRect(860, 505, 60, 16))
        self.LabelX_1.setObjectName("LabelX_1")
        self.LabelHSpan_1 = QtWidgets.QLabel(self.map)
        self.LabelHSpan_1.setGeometry(QtCore.QRect(940, 480, 60, 16))
        self.LabelHSpan_1.setObjectName("LabelHSpan_1")
        self.DeltaY_1 = QtWidgets.QLineEdit(self.map)
        self.DeltaY_1.setGeometry(QtCore.QRect(1030, 530, 61, 24))
        self.DeltaY_1.setObjectName("DeltaY_1")
        self.px_sel1 = QtWidgets.QCheckBox(self.map)
        self.px_sel1.setGeometry(QtCore.QRect(870, 478, 41, 21))
        self.px_sel1.setObjectName("px_sel1")
        self.HCutOff_1 = QtWidgets.QSlider(self.map)
        self.HCutOff_1.setGeometry(QtCore.QRect(840, 420, 251, 22))
        self.HCutOff_1.setMaximum(100)
        self.HCutOff_1.setProperty("value", 100)
        self.HCutOff_1.setOrientation(QtCore.Qt.Horizontal)
        self.HCutOff_1.setInvertedAppearance(False)
        self.HCutOff_1.setInvertedControls(False)
        self.HCutOff_1.setObjectName("HCutOff_1")
        self.Bilateral_1 = QtWidgets.QCheckBox(self.map)
        self.Bilateral_1.setGeometry(QtCore.QRect(1020, 380, 101, 20))
        self.Bilateral_1.setChecked(True)
        self.Bilateral_1.setObjectName("Bilateral_1")
        self.LabelStep_1 = QtWidgets.QLabel(self.map)
        self.LabelStep_1.setGeometry(QtCore.QRect(1040, 480, 60, 16))
        self.LabelStep_1.setObjectName("LabelStep_1")
        self.DeltaX_1 = QtWidgets.QLineEdit(self.map)
        self.DeltaX_1.setGeometry(QtCore.QRect(1030, 500, 61, 24))
        self.DeltaX_1.setObjectName("DeltaX_1")
        self.SpanX_1 = QtWidgets.QDoubleSpinBox(self.map)
        self.SpanX_1.setGeometry(QtCore.QRect(930, 500, 91, 24))
        self.SpanX_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpanX_1.setObjectName("SpanX_1")
        self.IntY_sel1 = QtWidgets.QCheckBox(self.map)
        self.IntY_sel1.setGeometry(QtCore.QRect(1100, 530, 51, 21))
        self.IntY_sel1.setObjectName("IntY_sel1")
        self.cmap_inv_sel1 = QtWidgets.QCheckBox(self.map)
        self.cmap_inv_sel1.setGeometry(QtCore.QRect(1100, 420, 51, 21))
        self.cmap_inv_sel1.setObjectName("cmap_inv_sel1")
        self.Cmaps_1 = QtWidgets.QComboBox(self.map)
        self.Cmaps_1.setGeometry(QtCore.QRect(850, 390, 151, 26))
        self.Cmaps_1.setEditable(False)
        self.Cmaps_1.setCurrentText("")
        self.Cmaps_1.setObjectName("Cmaps_1")
        self.LabelY_1 = QtWidgets.QLabel(self.map)
        self.LabelY_1.setGeometry(QtCore.QRect(860, 535, 60, 16))
        self.LabelY_1.setObjectName("LabelY_1")
        self.tabWidget.addTab(self.map, "")
        self.ROI = QtWidgets.QWidget()
        self.ROI.setObjectName("ROI")
        self.ROI_list = QtWidgets.QListWidget(self.ROI)
        self.ROI_list.setGeometry(QtCore.QRect(1020, 30, 131, 351))
        self.ROI_list.setObjectName("ROI_list")
        self.MainPlot_2 = PlotWidget(self.ROI)
        self.MainPlot_2.setGeometry(QtCore.QRect(470, 0, 351, 381))
        self.MainPlot_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MainPlot_2.setObjectName("MainPlot_2")
        self.EDCPlot_2 = PlotWidget(self.ROI)
        self.EDCPlot_2.setGeometry(QtCore.QRect(820, 0, 191, 381))
        self.EDCPlot_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.EDCPlot_2.setObjectName("EDCPlot_2")
        self.MDCPlot_2 = PlotWidget(self.ROI)
        self.MDCPlot_2.setGeometry(QtCore.QRect(470, 380, 351, 161))
        self.MDCPlot_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MDCPlot_2.setObjectName("MDCPlot_2")
        self.MapPlot_2 = PlotWidget(self.ROI)
        self.MapPlot_2.setGeometry(QtCore.QRect(20, 90, 321, 281))
        self.MapPlot_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.MapPlot_2.setObjectName("MapPlot_2")
        self.graphicsView_3 = GraphicsLayoutWidget(self.ROI)
        self.graphicsView_3.setGeometry(QtCore.QRect(20, 380, 371, 161))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.ROI_list_label = QtWidgets.QLabel(self.ROI)
        self.ROI_list_label.setGeometry(QtCore.QRect(1020, 10, 71, 16))
        self.ROI_list_label.setObjectName("ROI_list_label")
        self.HCutOff_3 = QtWidgets.QSlider(self.ROI)
        self.HCutOff_3.setGeometry(QtCore.QRect(840, 420, 251, 22))
        self.HCutOff_3.setMaximum(100)
        self.HCutOff_3.setProperty("value", 100)
        self.HCutOff_3.setOrientation(QtCore.Qt.Horizontal)
        self.HCutOff_3.setInvertedAppearance(False)
        self.HCutOff_3.setInvertedControls(False)
        self.HCutOff_3.setObjectName("HCutOff_3")
        self.SpanX_3 = QtWidgets.QDoubleSpinBox(self.ROI)
        self.SpanX_3.setGeometry(QtCore.QRect(930, 500, 91, 24))
        self.SpanX_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpanX_3.setObjectName("SpanX_3")
        self.DeltaY_3 = QtWidgets.QLineEdit(self.ROI)
        self.DeltaY_3.setGeometry(QtCore.QRect(1030, 530, 61, 24))
        self.DeltaY_3.setObjectName("DeltaY_3")
        self.LabelHSpan_3 = QtWidgets.QLabel(self.ROI)
        self.LabelHSpan_3.setGeometry(QtCore.QRect(940, 480, 60, 16))
        self.LabelHSpan_3.setObjectName("LabelHSpan_3")
        self.Bilateral_3 = QtWidgets.QCheckBox(self.ROI)
        self.Bilateral_3.setGeometry(QtCore.QRect(1020, 380, 101, 20))
        self.Bilateral_3.setChecked(True)
        self.Bilateral_3.setObjectName("Bilateral_3")
        self.SpanY_3 = QtWidgets.QDoubleSpinBox(self.ROI)
        self.SpanY_3.setGeometry(QtCore.QRect(930, 530, 91, 24))
        self.SpanY_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpanY_3.setObjectName("SpanY_3")
        self.IntY_sel3 = QtWidgets.QCheckBox(self.ROI)
        self.IntY_sel3.setGeometry(QtCore.QRect(1100, 530, 51, 21))
        self.IntY_sel3.setObjectName("IntY_sel3")
        self.cmap_inv_sel3 = QtWidgets.QCheckBox(self.ROI)
        self.cmap_inv_sel3.setGeometry(QtCore.QRect(1100, 420, 51, 21))
        self.cmap_inv_sel3.setObjectName("cmap_inv_sel3")
        self.Cmaps_3 = QtWidgets.QComboBox(self.ROI)
        self.Cmaps_3.setGeometry(QtCore.QRect(850, 390, 151, 26))
        self.Cmaps_3.setEditable(False)
        self.Cmaps_3.setCurrentText("")
        self.Cmaps_3.setObjectName("Cmaps_3")
        self.px_sel_3 = QtWidgets.QCheckBox(self.ROI)
        self.px_sel_3.setGeometry(QtCore.QRect(870, 478, 41, 21))
        self.px_sel_3.setObjectName("px_sel_3")
        self.LabelX_3 = QtWidgets.QLabel(self.ROI)
        self.LabelX_3.setGeometry(QtCore.QRect(860, 505, 60, 16))
        self.LabelX_3.setObjectName("LabelX_3")
        self.IntX_sel3 = QtWidgets.QCheckBox(self.ROI)
        self.IntX_sel3.setGeometry(QtCore.QRect(1100, 500, 51, 21))
        self.IntX_sel3.setObjectName("IntX_sel3")
        self.DeltaX_3 = QtWidgets.QLineEdit(self.ROI)
        self.DeltaX_3.setGeometry(QtCore.QRect(1030, 500, 61, 24))
        self.DeltaX_3.setObjectName("DeltaX_3")
        self.LabelStep_3 = QtWidgets.QLabel(self.ROI)
        self.LabelStep_3.setGeometry(QtCore.QRect(1040, 480, 60, 16))
        self.LabelStep_3.setObjectName("LabelStep_3")
        self.LabelY_3 = QtWidgets.QLabel(self.ROI)
        self.LabelY_3.setGeometry(QtCore.QRect(860, 535, 60, 16))
        self.LabelY_3.setObjectName("LabelY_3")
        self.LCutOff_3 = QtWidgets.QSlider(self.ROI)
        self.LCutOff_3.setGeometry(QtCore.QRect(840, 450, 251, 22))
        self.LCutOff_3.setMaximum(100)
        self.LCutOff_3.setProperty("value", 0)
        self.LCutOff_3.setSliderPosition(0)
        self.LCutOff_3.setOrientation(QtCore.Qt.Horizontal)
        self.LCutOff_3.setInvertedAppearance(False)
        self.LCutOff_3.setInvertedControls(False)
        self.LCutOff_3.setObjectName("LCutOff_3")
        self.cmap_inv_sel4 = QtWidgets.QCheckBox(self.ROI)
        self.cmap_inv_sel4.setGeometry(QtCore.QRect(310, 30, 51, 21))
        self.cmap_inv_sel4.setObjectName("cmap_inv_sel4")
        self.Cmaps_4 = QtWidgets.QComboBox(self.ROI)
        self.Cmaps_4.setGeometry(QtCore.QRect(60, 0, 151, 26))
        self.Cmaps_4.setEditable(False)
        self.Cmaps_4.setCurrentText("")
        self.Cmaps_4.setObjectName("Cmaps_4")
        self.HCutOff_4 = QtWidgets.QSlider(self.ROI)
        self.HCutOff_4.setGeometry(QtCore.QRect(50, 30, 251, 22))
        self.HCutOff_4.setMaximum(100)
        self.HCutOff_4.setProperty("value", 100)
        self.HCutOff_4.setTracking(True)
        self.HCutOff_4.setOrientation(QtCore.Qt.Horizontal)
        self.HCutOff_4.setInvertedAppearance(False)
        self.HCutOff_4.setInvertedControls(False)
        self.HCutOff_4.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.HCutOff_4.setObjectName("HCutOff_4")
        self.LCutOff_4 = QtWidgets.QSlider(self.ROI)
        self.LCutOff_4.setGeometry(QtCore.QRect(50, 60, 251, 22))
        self.LCutOff_4.setMaximum(100)
        self.LCutOff_4.setProperty("value", 0)
        self.LCutOff_4.setSliderPosition(0)
        self.LCutOff_4.setOrientation(QtCore.Qt.Horizontal)
        self.LCutOff_4.setInvertedAppearance(False)
        self.LCutOff_4.setInvertedControls(False)
        self.LCutOff_4.setObjectName("LCutOff_4")
        self.setROI = QtWidgets.QPushButton(self.ROI)
        self.setROI.setGeometry(QtCore.QRect(350, 110, 113, 32))
        self.setROI.setObjectName("setROI")
        self.saveROI = QtWidgets.QPushButton(self.ROI)
        self.saveROI.setGeometry(QtCore.QRect(350, 280, 113, 32))
        self.saveROI.setObjectName("saveROI")
        self.ROI_from_map = QtWidgets.QRadioButton(self.ROI)
        self.ROI_from_map.setGeometry(QtCore.QRect(360, 160, 100, 20))
        self.ROI_from_map.setObjectName("ROI_from_map")
        self.ROI_from_disp = QtWidgets.QRadioButton(self.ROI)
        self.ROI_from_disp.setGeometry(QtCore.QRect(360, 200, 100, 20))
        self.ROI_from_disp.setObjectName("ROI_from_disp")
        self.ROI_select_label = QtWidgets.QLabel(self.ROI)
        self.ROI_select_label.setGeometry(QtCore.QRect(360, 140, 101, 16))
        self.ROI_select_label.setObjectName("ROI_select_label")
        self.ROI_select_label_2 = QtWidgets.QLabel(self.ROI)
        self.ROI_select_label_2.setGeometry(QtCore.QRect(360, 220, 101, 16))
        self.ROI_select_label_2.setObjectName("ROI_select_label_2")
        self.tabWidget.addTab(self.ROI, "")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(10, 590, 113, 32))
        self.close.setObjectName("close")
        self.save_and_exit = QtWidgets.QPushButton(self.centralwidget)
        self.save_and_exit.setGeometry(QtCore.QRect(130, 590, 113, 32))
        self.save_and_exit.setObjectName("save_and_exit")
        disp4d_panel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(disp4d_panel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 22))
        self.menubar.setObjectName("menubar")
        disp4d_panel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(disp4d_panel)
        self.statusbar.setObjectName("statusbar")
        disp4d_panel.setStatusBar(self.statusbar)

        self.retranslateUi(disp4d_panel)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(disp4d_panel)

    def retranslateUi(self, disp4d_panel):
        _translate = QtCore.QCoreApplication.translate
        disp4d_panel.setWindowTitle(_translate("disp4d_panel", "Display panel"))
        self.CursorMode.setText(_translate("disp4d_panel", "Cursor mode: Normal"))
        self.Label_xsel1.setText(_translate("disp4d_panel", "x1"))
        self.Label_xsel2.setText(_translate("disp4d_panel", "x2"))
        self.Bin_label.setText(_translate("disp4d_panel", "Bin"))
        self.IntX_sel1.setText(_translate("disp4d_panel", "Int."))
        self.LabelX_1.setText(_translate("disp4d_panel", "TextLabel"))
        self.LabelHSpan_1.setText(_translate("disp4d_panel", "Half span"))
        self.px_sel1.setText(_translate("disp4d_panel", "px."))
        self.Bilateral_1.setText(_translate("disp4d_panel", "Bilateral Link"))
        self.LabelStep_1.setText(_translate("disp4d_panel", "Step"))
        self.IntY_sel1.setText(_translate("disp4d_panel", "Int."))
        self.cmap_inv_sel1.setText(_translate("disp4d_panel", "Inv."))
        self.LabelY_1.setText(_translate("disp4d_panel", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.map), _translate("disp4d_panel", "Map Explorer"))
        self.ROI_list_label.setText(_translate("disp4d_panel", "ROI Select"))
        self.LabelHSpan_3.setText(_translate("disp4d_panel", "Half span"))
        self.Bilateral_3.setText(_translate("disp4d_panel", "Bilateral Link"))
        self.IntY_sel3.setText(_translate("disp4d_panel", "Int."))
        self.cmap_inv_sel3.setText(_translate("disp4d_panel", "Inv."))
        self.px_sel_3.setText(_translate("disp4d_panel", "px."))
        self.LabelX_3.setText(_translate("disp4d_panel", "TextLabel"))
        self.IntX_sel3.setText(_translate("disp4d_panel", "Int."))
        self.LabelStep_3.setText(_translate("disp4d_panel", "Step"))
        self.LabelY_3.setText(_translate("disp4d_panel", "TextLabel"))
        self.cmap_inv_sel4.setText(_translate("disp4d_panel", "Inv."))
        self.setROI.setText(_translate("disp4d_panel", "Set ROI"))
        self.saveROI.setText(_translate("disp4d_panel", "Save ROI"))
        self.ROI_from_map.setText(_translate("disp4d_panel", "From map"))
        self.ROI_from_disp.setText(_translate("disp4d_panel", "From disp"))
        self.ROI_select_label.setText(_translate("disp4d_panel", "------------->>"))
        self.ROI_select_label_2.setText(_translate("disp4d_panel", "<<-------------"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ROI), _translate("disp4d_panel", "ROI analysis"))
        self.close.setText(_translate("disp4d_panel", "Close"))
        self.save_and_exit.setText(_translate("disp4d_panel", "Save and Exit"))


from pyqtgraph import GraphicsLayoutWidget, PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    disp4d_panel = QtWidgets.QMainWindow()
    ui = Ui_disp4d_panel()
    ui.setupUi(disp4d_panel)
    disp4d_panel.show()
    sys.exit(app.exec_())
